### ISSUE TITLE
Dockerize build (to prepare for cd)

### ISSUE THREAD

**Issue by fisher60** [gurkult/reagurk#19]
We should utilize docker to build the production site and allow it to be served. 

Essentially we just need to build the site and save that build folder to the system. The file should be stored either in the root directory of this project, or if possible the directory above it (since that is where the webserver is currently looking for the build.)

The file system is as follows:

```
gurkult.com
--reagurk
----<project files and docker>
```
it is preferred that the build is placed in the `gurkult.com`  directory above the project's root directory, however this may be annoying/difficult to implement, so it is acceptable if the build is saved to in the project's root directory `reagurk`.

**Comment by saifmohamedo** [comment]
here
