### ISSUE TITLE
use media queries

### ISSUE THREAD

**Issue by vy0** [gurkult/reagurk#34]
media queries or just using a framework such as bootstrap will help your website be more responsive, for mobile devices it seems to mess up a bit

**Comment by gustavwilliam** [comment]
Right, so, the current one is only a placeholder site. When we’re working on the main site, I agree that we should keep things mobile responsive.

**Comment by dawnofmidnight** [comment]
I believe our updated setup with Tailwind handles this very well.

**Comment by vy0** [comment]
just checked it out and it looks really nice, only issue i have is the whitespace at the bottom of the page. if possible, just make the current elements full height and width.

**Comment by dawnofmidnight** [comment]
There are currently components being worked on that will fill up that space, such as the footer.

**Comment by fisher60** [comment]
Closing due to deprecated by tailwind
