### ISSUE TITLE
Add image to preview link/embed

### ISSUE THREAD

**Issue by fisher60** [gurkult/reagurk#43]
We need to add meta tags for an image to be loaded in the discord embed when the site is linked to.

**Comment by shikhar13012001** [comment]
I would like to work on this, Please assign it to me

**Comment by fisher60** [comment]
@shikhar13012001 Awesome, I have assigned you. I am thinking we can use the `crown` asset for the preview since it would fit nicely. I would be open to using the logo instead, but worried about the sizing.

**Comment by shikhar13012001** [comment]
@fisher60 Sir, how  should I add the meta tags in this project , like should i put them in just in basic index.html  int public folder or use react-meta-tags.
### For now I have made use of the first method and I have come up with these mock ups, please tell me any change if you need or change in method of the application
![](https://i.ibb.co/0m2YDVz/Screenshot-594.png)
<br/>
![](https://i.ibb.co/3RB1z6G/Screenshot-595.png)
<br/>
![](https://i.ibb.co/PMJbsCx/Screenshot-596.png)

**Comment by fisher60** [comment]
@shikhar13012001 Hello, awesome. I actually really like the second one (the logo, inline with the text) as it is fairly compact. You can use whichever method you think is best to make things clear, understandable, and easily modifiable in the future--either index or react-meta-tags.

**Comment by shikhar13012001** [comment]
> @shikhar13012001 Hello, awesome. I actually really like the second one (the logo, inline with the text) as it is fairly compact. You can use whichever method you think is best to make things clear, understandable, and easily modifiable in the future--either index or react-meta-tags.

Ok sir I will do as said , thankyou

**Comment by dawnofmidnight** [comment]
I personally think that just using index.html is fine as we have no real need for that extra dependency.

**Comment by shikhar13012001** [comment]
> I personally think that just using index.html is fine as we have no real need for that extra dependency.

Ok, sir, I will do the changes ASAP, thank you for clarification
