### ISSUE TITLE
move meta data in index.tsx to index.html to remove multiple <head> tags

### ISSUE THREAD

**Issue by fisher60** [gurkult/reagurk#51]
We should not have multiple <head> tags in our site, therefore all the data in the head tags in index.tsx should be moved to index.html.

**Comment by RishiKumarRay** [comment]
we have to move all head tags only? i wanna give a try on this issue

**Comment by RishiKumarRay** [comment]
generated a PR #53

**Comment by RishiKumarRay** [comment]
@dawnofmidnight can  you review the changes

**Comment by RishiKumarRay** [comment]
@dawnofmidnight I have updated all the changes and removed duplicated and about that metadata.json , i dont know much so can we discuss it over other issue and and i will fix them too in another PR?

**Comment by dawnofmidnight** [comment]
All you have to do in the manifest.json is copy the title and description fields here to the ones there.

**Comment by RishiKumarRay** [comment]
@dawnofmidnight Where and how to do it , I didn't get it , can you give an example , here from the screenshot
![Screenshot from 2022-01-17 06-26-40](https://user-images.githubusercontent.com/87641376/149685480-b526c630-55c5-4e1e-bd3e-ae531bbf3a8a.png)

**Comment by RishiKumarRay** [comment]
@dawnofmidnight can you review and merge the changes i have done till now please , I haven't worked with manifest.json earlier so i don't know anything about also i tried but didn't got anything. Please do merge the PR as it solves everything that was mentioned in issue 51

**Comment by RishiKumarRay** [comment]
@dawnofmidnight Hi, Can you please merge the changes
